### PR TITLE
The Neconing Part 1

### PR DESCRIPTION
**Pull request by Siuolplex**
I still have a ways to go but heres the start of it

### CODE REVIEW

**Comment by Siuolplex** [comment]
BTW its still the old neco type swapping method not the one we discussed in dms and as I mentioned plenty of work is still left

**Comment by Siuolplex** [comment]
Alright whats in as of rn: 
- All 4 Necos have been fully completed along with their items (Ignoring texture revamps and recipes along with maybe sounds)
- Neco swapping transformation method is what you mentioned, if you are a Neco already I might make it not require a cat idk

What I still might do:
- Do we want to add alt sounds for each Neco into it? I know that there might be some complications from that
- As mentioned earlier I (Or yourself as you are a much better artist than me lol) needs to redo some of the textures I added to make them work better.
- Also moving upwards into a block causes infinite explosions so can we keep that

**Comment by Siuolplex** [comment]
I added the sounds please cry

**Comment by Siuolplex** [comment]
All thats left for the most part is simply recipes

**Comment by Arathain** [comment]
alright, I'll go through recipes & textures either today or tmr

**Pull request merged**
